services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: radare
      POSTGRES_USER: radare
      POSTGRES_PASSWORD: radare
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "radare"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    container_name: radare-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=radare
      - DB_PASSWORD=radare
      - DB_NAME=radare
      - DB_SSLMODE=disable
      - JWT_SECRET=your_secret_key
      - PORT=8080

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    container_name: radare-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8080

networks:
  app-network:
    driver: bridge
